version: '3.8'

services:
  # Ultron Standalone Application
  ultron:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ultron-standalone  
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      # Supabase credentials must be provided externally for security
      # Use a .env file or secrets management system to set these values:
      # SUPABASE_URL=your_supabase_project_url
      # SUPABASE_ANON_KEY=your_supabase_anonymous_key
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "app=ultron"
      - "version=2.5.20"
    networks:
      - ultron-network

networks:
  ultron-network:
    driver: bridge 